from abc import ABC, abstractmethod
from typing import Any, Dict

class BaseLLM(ABC):
    """
    Abstract Base Class for Large Language Models (LLMs).
    """

    @abstractmethod
    def generate(self, prompt: str, **kwargs) -> str:
        """
        Generate a response based on the given prompt.
        :param prompt: The input prompt to the LLM.
        :return: The response generated by the LLM.
        """
        pass
